---
# Build and push 'latest' Docker image.

kind: pipeline
type: docker
name: Docker build

platform:
  os: linux
  arch: amd64

steps:
  # Push the docker image on main/tags.
  - name: Push Docker Image
    image: plugins/docker
    settings:
      repo: grafana/celery-exporter
      config:
        from_secret: dockerconfigjson
      build_args:
        - DOCKER_REPO=grafana/celery-exporter
        - DOCKER_VERSION=latest
        - VCS_REF=$DRONE_COMMIT_SHA
      tags:
        - latest
    when:
      ref:
        - refs/heads/main
        - refs/heads/add-drone
        - refs/tags/v*.*.*

---
kind: secret
name: dockerconfigjson
get:
  path: secret/data/common/gcr
  name: .dockerconfigjson
---
kind: secret
name: gcr_admin
get:
  path: infra/data/ci/gcr-admin
  name: .dockerconfigjson
