---
# Build and push 'latest' Docker image.

kind: pipeline
type: docker
name: Docker build

platform:
  os: linux
  arch: amd64

steps:
  # Push the docker image on main/tags.
  - name: Build and push Docker Image
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      repo: grafana/celery-exporter
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/heads/main
        - refs/heads/add-drone
        - refs/tags/v*.*.*

---
# Dockerhub
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: docker_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: docker_password
